# Configuration file for flask-demo
#
# Used as ConfigMap to run the server in k8s:
#
#   kc create configmap frontend-config --from-file=config.yaml

config:
    seed: 2345
    clients: 5

response:
    max: 99
    prefix: "flask-"

db:
  # Here the 'hostname' must match the Service `name`
  # fronting the backend (see backend-service.yaml)
  uri: "mongodb://backend:27017/my-db"
  collection: "sampledata"
