# Copyright (c) 2020 AlertAvert.com  All rights reserved.
# Created by M. Massenzio, 2020-11-24
#
# Configuration file for local development.
# Each entry replaces the CLI option of the same name (see run_server.py, parse_args())
#
# Command-line args passed at runtime take priority over the values in the config file.

workdir: "/var/local/share/k8s-web"
db-uri: "mongodb://localhost:27017"
collection: "dev-data"
secret-key: "don7u53th15"
debug: true
