# Copyright (c) 2020 AlertAvert.com  All rights reserved.
# Created by M. Massenzio, 2020-11-24
#
# Configuration file for local development.
#
# Run Mongo as a Container with:
#   $ docker run --rm -d -p27017:27017 --name mongodb mongo:3.7
#
# Run the server with:
#   $ ./run_server.py --debug -p 5500 --config-file ../dev-config.yaml
#
server:
  workdir: /var/local/share/k8s-web
db:
  uri: "mongodb://localhost:27017/dev-db"
  collection: "entities"
