apiVersion: v1
kind: Pod
metadata:
    name: flask-demo
    namespace: apps
    labels:
      app: web-server
      rel: unstable

spec:
  containers:
    - image: massenz/simple-flask:0.2.0
      name: flask-demo
      ports:
        - containerPort: 5050
          protocol: TCP
      livenessProbe:
        httpGet:
          path: "/health"
          port: 5050
