# ReplicaSet for Flask Demo

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-cluster
  namespace: apps
  labels:
    app: web-frontend
    rel: staging

spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server

  template:
    metadata:
      labels:
        app: web-server
        rel: staging

    spec:
      volumes:
      - name: config
        configMap:
          name: frontend-config

      containers:
      - image: docker.apple.com/amp-sre/simple-flask:0.3.1
        name: flask-demo
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: https
          containerPort: 8443
          protocol: TCP

        volumeMounts:
        - name: config
          mountPath: "/etc/flask"
          readOnly: true


        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: SECURE_PORT
          value: "8443"

        livenessProbe:
          httpGet:
            path: "/health"
            port: 8080
