# Example configuration file

server:
  workdir: /tmp

db:
  # Here the 'hostname' must match the Service `name`
  # fronting the backend (see backend-service.yaml)
  uri: "mongodb://localhost:27017/test-db"
  collection: "exmaples"
