# Copyright (c) 2020 AlertAvert.com  All rights reserved.
# Created by M. Massenzio, 2020-11-27
#
# Starts the Mongo Replica Set.

FROM mongo:3.7
ENV REPLICAS=3
ENV NODE_NAME="mongo-node"
ENV CLUSTER_NAME="mongo-cluster"
ENV MONGO_URL="${NODE_NAME}-0.${CLUSTER_NAME}"

WORKDIR /opt/mongo-replicas

ADD mongo/mongo-replicas.js ./
ADD mongo/setup-replicas ./
RUN chmod +x ./setup-replicas

ENTRYPOINT ./setup-replicas
