# Yaml configuration file for tlogger


tlogger:
  data_file: 'data_upload.log'

  remote_server: "https://mzuserxp.itunes.apple.com/WebObjects/MZUserXP.woa/wa/ReceiptStats"

  # This allows the mobile app to upload the data back to this server; the IP is retrieved via
  # the AWS instance metadata service:
  #     http://169.254.169.254/latest/meta-data/public-ipv4
  # and the PORT from the runtime configuration (--port).
  # See: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
  local_server: "http://{ip}:{port}/api/1/upload"
