# Persistent Volume claim backed by the
# default storage class, created dynamically.
#
# Using this (see mongo-pod.yaml) does not require
# creating a Persistent Volume first.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-1

spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-2

spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-3

spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce
