# Configuration file for flask-demo
#
# Used as ConfigMap to run the server in k8s:
#
#   kc create configmap frontend-config --from-file=frontend-config.yaml

server:
  workdir: /var/lib/flask

db:
  # Here the 'hostname' must match the Service `name`
  # fronting the backend (see backend-service.yaml)
  uri: "mongodb://backend:27017/my-db"
  collection: "sampledata"
