# Persistent Volume claim backed by the
# default storage class, created dynamically.
#
# Using this (see mongo-pod.yaml) does not require
# creating a Persistent Volume first.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: amp

spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce
