# A DB service, backed by a MongoDB Pod
# Using a "stateful" service (with a Persistent Volume)
#
# Reachable at URL: mongodb://backend:27017/db_name

# Headless service for the StatefulSet.
apiVersion: v1
kind: Service
metadata:
  name: backend

spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017

---
# The "stateful" Pod which
# uses a PVC to back its persistent data.
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: "data-cluster-1"
    labels:
      cluster: "mongodb-123-us-west-1"
      rel: "mongo-3.7"
spec:
  serviceName: backend
  selector:
    matchLabels:
      # Must match the {{.spec.metadata.labels}} in the pod {{.template}} below
      app: mongodb

  # TODO: scale this up to three nodes, but need odd MongoDB ReplicaSet configuration.
  replicas: 1

  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - image: "mongo:3.7"
          name: mongodb
          imagePullPolicy: "Always"
          ports:
          - containerPort: 27017
            protocol: TCP
          volumeMounts:
          - name: mongo-pvc
            mountPath: /data/db

  volumeClaimTemplates:
  - metadata:
      # Here the `name` MUST match the name in the `volumeMounts`
      name: mongo-pvc
    spec:
      resources:
        requests:
          storage: 20Mi
      accessModes:
      - ReadWriteOnce
