# Persistent Volume claims backed by the
# default storage class, created dynamically.

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-1

spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-2

spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-3

spec:
  resources:
    requests:
      storage: 100Mi
  accessModes:
  - ReadWriteOnce
